In [1]:
import numpy as np

In [27]:
x = np.array([1, 5, 2])
y = np.array([7, 4, 1])
x + y

array([8, 9, 3])

In [29]:
x-y

array([-6,  1,  1])

In [30]:
x*y

array([ 7, 20,  2])

In [31]:
x/y

array([0.14285714, 1.25      , 2.        ])

In [2]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 

In [3]:
print ('First array:') 
print (a) 
print ('\n')  

print( 'Second array:') 
b = np.array([10,10,10]) 
print (b )

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


In [5]:
print( 'Add the two arrays:' )
print( np.add(a,b) )

Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


In [6]:
print ('Subtract the two arrays:') 
print (np.subtract(a,b) )
  

Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


In [7]:
print ('Multiply the two arrays:' )
print (np.multiply(a,b)) 

Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


In [8]:
print ('Divide the two arrays:') 
print( np.divide(a,b))

Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


numpy.reciprocal()

This function returns the reciprocal of argument, element-wise. For elements with absolute values larger than 1, the result is always 0 and for integer 0, overflow warning is issued. Example: 

In [9]:
arr = np.array([25, 1.33, 1, 1, 100])
 
print('Our array is:')
print(arr)

Our array is:
[ 25.     1.33   1.     1.   100.  ]


In [10]:
print('\nAfter applying reciprocal function:')
print(np.reciprocal(arr))


After applying reciprocal function:
[0.04      0.7518797 1.        1.        0.01     ]


In [11]:
arr2 = np.array([25], dtype = int)
print('\nThe second array is:')
print(arr2)


The second array is:
[25]


In [12]:
print('\nAfter applying reciprocal function:')
print(np.reciprocal(arr2))


After applying reciprocal function:
[0]


# numpy.power() 

This function treats elements in the first input array as the base and returns it raised to the power of the corresponding element in the second input array. 

In [13]:
 
arr = np.array([5, 10, 15])
 
print('First array is:')
print(arr)
 


First array is:
[ 5 10 15]


In [14]:
print('\nApplying power function:')
print(np.power(arr, 2))
 



Applying power function:
[ 25 100 225]


In [15]:
print('\nSecond array is:')
arr1 = np.array([1, 2, 3])
print(arr1)
 



Second array is:
[1 2 3]


In [17]:
print('\nApplying power function again:')
print(np.power(arr, arr1))


Applying power function again:
[   5  100 3375]


# numpy.mod()

This function returns the remainder of division of the corresponding elements in the input array. The function numpy.remainder() also produces the same result. 

In [19]:
arr = np.array([5, 15, 20])
arr1 = np.array([2, 5, 9])
 
print('First array:')
print(arr)
 


First array:
[ 5 15 20]


In [20]:
print('\nSecond array:')
print(arr1)



Second array:
[2 5 9]


In [21]:
print('\nApplying mod() function:')
print(np.mod(arr, arr1))
 



Applying mod() function:
[1 0 2]


In [22]:
print('\nApplying remainder() function:')
print(np.remainder(arr, arr1))


Applying remainder() function:
[1 0 2]


# max()

In [23]:
a = np.array([10,20,30,40,50])
  
# find the maximum element in the array
b = np.max(a)
print(b)

50


# min()

In [24]:
a=np.array([10,20,30,40,50])
  
# find the minimum element in the array
b=np.min(a)
print(b)

10


# sum()

This function is used to return the sum of all elements of an array over specified axis. It is possible to add rows and column elements of an array.

In [25]:
a=np.array([1,2,3,4,5])
b=np.sum(a)
print(b)

15


# Matrices

In [26]:
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [32]:
x = np.matrix(np.arange(12).reshape((3,4)));
x

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [34]:
y = x[2]; y

matrix([[ 8,  9, 10, 11]])

In [41]:
(x == y)

matrix([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True]])

In [42]:
(x == y).all()

False

In [43]:
(x == y).all(0)

matrix([[False, False, False, False]])

In [44]:
(x == y).all(1)

matrix([[False],
        [False],
        [ True]])

Convert matrix into list

Syntax: matrix.tolist()
Return : Return a new list

In [107]:
# make matrix with numpy
mat = np.matrix('[4, 1, 12, 3]')
              
# applying matrix.tolist() method
m = mat.tolist()
    
print(m)

[[4, 1, 12, 3]]


# Transpose of matrix (numpy.matrix.T)

In [45]:
m = np.matrix('[1, 2; 3, 4]')
m

matrix([[1, 2],
        [3, 4]])

In [46]:
m.getT()

matrix([[1, 3],
        [2, 4]])

In [48]:
np.transpose(m)

matrix([[1, 3],
        [2, 4]])

In [50]:
a = np.array([1, 2, 3, 4])
a


array([1, 2, 3, 4])

In [51]:
np.transpose(a)

array([1, 2, 3, 4])

In [52]:
a = np.ones((1, 2, 3))
np.transpose(a, (1, 0, 2)).shape

(2, 1, 3)

In [59]:
a = np.ones((2, 3, 4, 5))
np.transpose(a).shape

(5, 4, 3, 2)

In [61]:
arr1 = [[1, 2, 3], [4, 5, 6]]

arr1_transpose = np.transpose(arr1)
arr1_transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

# Generate random number

Syntax :

random.randint(low, high=None, size=None, dtype=int)

In [62]:
np.random.rand(3,2)

array([[0.39805701, 0.7396424 ],
       [0.92589024, 0.27011706],
       [0.81209714, 0.06261954]])

In [65]:
np.random.randint(2, size=10)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0])

In [66]:
np.random.randint(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
# Generate a 2 x 4 array of ints between 0 and 4, inclusive:
np.random.randint(5, size=(2, 4))

array([[4, 3, 0, 3],
       [4, 1, 1, 2]])

In [68]:
# Generate a 1 x 3 array with 3 different upper bounds
np.random.randint(1, [3, 5, 10])

array([2, 2, 9])

In [69]:
# Generate a 1 by 3 array with 3 different lower bounds
np.random.randint([1, 5, 7], 10)

array([9, 9, 9])

numpy.random.randn

random.randn(d0, d1, ..., dn)

Return a sample (or samples) from the “standard normal” distribution.

In [70]:
np.random.randn()

0.20074266273953198

In [71]:
# Two-by-four array of samples from the normal distribution with mean 3 and standard deviation 2.5:

3 + 2.5 * np.random.randn(2, 4)

array([[ 5.42452629,  5.2260377 ,  5.0039538 ,  7.00871916],
       [ 4.0783687 , -0.28167103,  4.77659881, -2.51240896]])

# numpy.random.random

random.random(size=None)
Return random floats in the half-open interval [0.0, 1.0). Alias for random_sample to ease forward-porting to the new random AP

In [73]:
np.random.random()

0.3991851744971916

In [74]:
# Using numpy random randint() to generate a random number
random_number = np.random.randint(12)

print(random_number)

8


In [75]:
# Using numpy random uniform to create random samples
sample = np.random.uniform(-1,0,1000)
# Uniform Distribution check
print(np.all(sample >= -1))
print(np.all(sample < 0))

True
True


In [76]:

# Using random.rand() to generate a random float
random_float = np.random.rand()

print(random_float)

0.9540513514879408


In [77]:
# Using random.randint() to generate random array
arr=np.random.randint(20, size=(4))

print(arr)

[13  5  8 19]


In [78]:
# Using random.rand() to generate random array of float values
arr=np.random.rand(4)

print(arr)

[0.58288599 0.22420228 0.61516864 0.36718532]


In [80]:

# Using numpy random choice() from numpy.random() module to get a random choice from an array
random_choice = np.random.choice([1, 2, 4, 5])

print(random_choice)

1


# numpy.unique

In [81]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [84]:
a = np.array([[1, 1], [2, 3]])
np.unique(a)

array([1, 2, 3])

In [87]:
# Return the unique rows of a 2D array

a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=0)

array([[1, 0, 0],
       [2, 3, 4]])

In [88]:
# Return the indices of the original array that give the unique values:

In [89]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices = np.unique(a, return_index=True)
u

array(['a', 'b', 'c'], dtype='<U1')

In [90]:
indices

array([0, 1, 3], dtype=int64)

In [91]:
a[indices]

array(['a', 'b', 'c'], dtype='<U1')

In [93]:
# Reconstruct the input array from the unique values and inverse:
a = np.array([1, 2, 6, 4, 2, 3, 2])
u, indices = np.unique(a, return_inverse=True)
u


array([1, 2, 3, 4, 6])

In [94]:
indices

array([0, 1, 4, 3, 1, 2, 1], dtype=int64)

In [95]:
u[indices]

array([1, 2, 6, 4, 2, 3, 2])

In [96]:
# Reconstruct the input values from the unique values and counts:
a = np.array([1, 2, 6, 4, 2, 3, 2])
values, counts = np.unique(a, return_counts=True)
values

array([1, 2, 3, 4, 6])

In [97]:
counts

array([1, 3, 1, 1, 1], dtype=int64)

In [98]:
np.repeat(values, counts)

array([1, 2, 2, 2, 3, 4, 6])

In [101]:
array = np.array([1,1,1,2,3,4,4,4])

unique, counts = np.unique(array, return_counts=True)

result = np.column_stack((unique, counts)) 
print (result)

[[1 3]
 [2 1]
 [3 1]
 [4 3]]


# Count()

The numpy.core.defchararray.count() function returns an array with the number of non-overlapping occurrences of substring sub in the range [start, end].

In [102]:
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
c

array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')

In [103]:
np.char.count(c, 'A')

array([3, 1, 1])

In [104]:
np.char.count(c, 'aA')

array([3, 1, 0])

In [105]:
 np.char.count(c, 'A', start=1, end=4)

array([2, 1, 1])

In [106]:
np.char.count(c, 'b', start=1, end=3)

array([0, 0, 1])