# Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)



[1 2 3 4 5]


In [2]:
print(type(arr))

<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

Use a tuple to create a NumPy array:

In [8]:


arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


# Dimensions in Arrays

0-D Arrays


0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [9]:

arr = np.array(42)

print(arr)


42


1-D Arrays


An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [10]:


arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3-D arrays


An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [14]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [15]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [16]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Heading filled with 0's and 1's

numpy.zeros()

Python’s Numpy module provides a function to create a numpy array of given shape & type and all values in it initialized with 0’s i.e.

numpy.zeros(shape, dtype=float, order='C')
Arguments:

shape : Shape of the numpy array. Single int or sequence of int.
dtype : (Optional) Data type of elements. Default is float64.
order : (Optional) Order in which data is stored in multi-dimension array i.e. in row major(‘F’) or column major (‘C’). Default is ‘C’.

In [17]:
arr = np.zeros(5)
print('Contents of the Numpy Array : ' , arr)

Contents of the Numpy Array :  [0. 0. 0. 0. 0.]


Here, in shape argument we passed 5. So, it returned a flattened numpy array of 5 zeros.

In [18]:
arr = np.zeros((5, 6))
print('Contents of the Numpy Array : \n', arr)
print('Data Type of elements in  Array : ', arr.dtype)

Contents of the Numpy Array : 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Data Type of elements in  Array :  float64


In [19]:
# create a 2D numpy array with 5 rows &amp; 6 columns filled with 0's and int data type
arr = np.zeros((5, 6) , dtype=np.int64)
print('Contents of the Numpy Array : \n', arr)

Contents of the Numpy Array : 
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


numpy.ones()


Python’s Numpy module provides a function to create a numpy array of given shape & type and all values in it initialized with 1’s i.e.

numpy.ones(shape, dtype=float, order='C')
Arguments:

shape : Shape of the numpy array. Single int or sequence of int.
dtype : (Optional) Data type of elements. Default is float64.
order : (Optional) Order in which data is stored in multi-dimension array i.e. in row major(‘F’) or column major (‘C’). Default is ‘C’.

In [20]:
# create a 1D numpy array with 5 ones filled in it
arr = np.ones(5)
print('Contents of the Numpy Array : ' , arr)

Contents of the Numpy Array :  [1. 1. 1. 1. 1.]


In [21]:
# create a 2D numpy array with 3 rows &amp; 4 columns, filled with 1's
arr = np.ones((3, 4))
print('Contents of the Numpy Array : \n', arr)
print('Data Type of elements in  Array : ', arr.dtype)

Contents of the Numpy Array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Data Type of elements in  Array :  float64


In [22]:
# create a 2D numpy array with 3 rows &amp; 4 columns filled with 1's and int data type
arr = np.zeros((3, 4) , dtype=np.int64)
print('Contents of the Numpy Array : \n', arr)

Contents of the Numpy Array : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Create empty array

Python’s numpy module provides a function empty() to create new arrays,

numpy.empty(shape, dtype=float, order='C')

It accepts shape and data type as arguments.

Returns a new array of given shape and data type but without initializing entries. It means the returned numpy array will contain garbage values.

If data type argument is not provided then the default data type of all entries in the returned numpy array will be float.

Let’s use this empty() function to create an empty numpy array of different shape and data types.

numpy.empty(shape, dtype=float, order='C', *, like=None)
Where:

shape describes the shape of the empty array. It can be a tuple or a singular integer value.

dtype is an optional parameter that determines the datatype for the array elements. By default, this is numpy.float64.

order is an optional parameter that specifies how to store the multidimensional data in memory. The options are:

‘C’ for C-style row-major form
‘F’ for Fortran-style column-major form.
like is an optional parameter. It is a reference object that makes it possible to create non-NumPy arrays.

Each of these parameters serves a useful purpose. However, in this guide, we are only going to focus on the mandatory shape parameter.

Create an empty 1D Numpy array of given length :

In [26]:
# Create an empty 1D Numpy array of length 5
arr = np.empty(0)
print(arr)

[]


For instance, let’s create an empty 2D array:

In [28]:
arr = np.empty([2, 3])
print(arr) #Output (contains arbitrary values due to the uninitialized elements)

[[4.24399158e-314 8.48798317e-314 1.27319747e-313]
 [4.24399158e-314 8.48798317e-314 1.27319747e-313]]


In [29]:
# Create an empty 3D Numpy array
empty_array = np.empty((2, 3, 3))
print(empty_array)

[[[1.37962049e-306 1.24610791e-306 1.11260959e-306]
  [1.69109959e-306 9.34603679e-307 1.42419802e-306]
  [1.78019082e-306 4.45061456e-308 1.24612081e-306]]

 [[1.37962049e-306 9.34597567e-307 1.29061821e-306]
  [1.78019625e-306 1.11255866e-306 8.90098127e-307]
  [9.34609790e-307 3.91792279e-317 2.65249474e-312]]]


In [30]:
# Create an empty Numpy array of 5 integers
empty_array = np.empty(5, dtype=int)
print(empty_array)

[1 2 3 4 5]


In [31]:
# Create an empty Numpy array of 5 Complex Numbers
empty_array = np.empty(5, dtype=complex)
print(empty_array)

[nan+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]


In [32]:
# Create an empty Numpy array of 5 strings of length 3, You also get an array with binary strings
empty_array = np.empty(5, dtype='S3')
print(empty_array)

[b'\xa0\x8b\x8a' b'\xfc\x08\x02' b'' b'' b'']


# Create array with range of elements

The arange() works like the range function in python. It is used to create a list of integers within the range of numbers. 

Syntax

numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray

start: This is the number the array values begin.
    
stop: This number indicates the end of the array. Note, however, that this number is not included in the array.
    
step:  This is the spacing between consecutive indices. By default, it is set to 1 and so integers are within the start and stop value is returned. If set to 2, a number is skipped.
    
Note that the step cannot be set to zero. Else, a  ZeroDivisionError will be returned. 


print(np.arange(0, 15, 2))

In [37]:
# or
print(np.arange(start=0, stop=15, step=2))

[ 0  2  4  6  8 10 12 14]


Using the arange function() with 2 arguments.

If you are defining just 2 arguments, without keywords, the arguments are the start and end arguments. In this case, the step argument is set to one. Which implies that the integers will be printed consecutively. The example below prints the numbers between 0 and 15.

In [38]:
print(np.arange(0, 15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


How to Count Backwards with the step argument

he start value must be greater than the end value for it to run. So say we wish to return a list from 15 to 1 backwards, the start value is set to 15 while the end value is set to 1. The step is set to -1. See the code below.

In [39]:
print(np.arange(15, 0, -1))

[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


Using the linspace function


The linspace function is used to create an array of evenly spaced elements. When the linspace function is called, it receives 3 required arguments. It however has 4 arguments to be defined as shown in its syntax below.

Syntax:

numpy.linspace(start, stop, num, endpoint)

In [40]:
print(np.linspace(1, 3, 60))

[1.         1.03389831 1.06779661 1.10169492 1.13559322 1.16949153
 1.20338983 1.23728814 1.27118644 1.30508475 1.33898305 1.37288136
 1.40677966 1.44067797 1.47457627 1.50847458 1.54237288 1.57627119
 1.61016949 1.6440678  1.6779661  1.71186441 1.74576271 1.77966102
 1.81355932 1.84745763 1.88135593 1.91525424 1.94915254 1.98305085
 2.01694915 2.05084746 2.08474576 2.11864407 2.15254237 2.18644068
 2.22033898 2.25423729 2.28813559 2.3220339  2.3559322  2.38983051
 2.42372881 2.45762712 2.49152542 2.52542373 2.55932203 2.59322034
 2.62711864 2.66101695 2.69491525 2.72881356 2.76271186 2.79661017
 2.83050847 2.86440678 2.89830508 2.93220339 2.96610169 3.        ]


In [41]:
start_val = int(input("Enter starting value: "))
end_val = int(input("Enter ending value: "))
Step_val = int(input("Enter Step value: "))
print(np.arange(start_val, end_val, Step_val))

Enter starting value: 1
Enter ending value: 20
Enter Step value: 3
[ 1  4  7 10 13 16 19]


In [42]:

arr = np.array([1,3,5,7,10,2,4,6,8,10,36])
print("Original Array:\n",arr)

result = np.where(np.logical_and(arr>=4, arr<=20))
print(result)

Original Array:
 [ 1  3  5  7 10  2  4  6  8 10 36]
(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)


# Sorting of array using np.sort()

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [43]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [44]:
# Sort the array alphabetically:

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [46]:
# Boolean
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


Sorting a 2-D Array

If you use the sort() method on a 2-D array, both arrays will be sorted:

In [47]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [55]:
arr = np.array([['orange','mango','grapes'], ['banana','cherry','apple'], ['papaya','watermelon','jackfruit']]) 
arr2 = np.sort(arr)  
arr2

array([['grapes', 'mango', 'orange'],
       ['apple', 'banana', 'cherry'],
       ['jackfruit', 'papaya', 'watermelon']], dtype='<U10')

In [60]:
array = np.array([[3, 2, 4], [5, 0, 1]])
array_copy = np.sort(array)[::-1]
array_copy

array([[0, 1, 5],
       [2, 3, 4]])

In [61]:
array = np.array([5,8,6,12])

# Use numpy.ndarray.sort() to sort 
# An array in descending order
array[::-1].sort()
print(array)

[12  8  6  5]


In [63]:
#  Sort multi dimensional  NumPy arrays   
arr = np.array([[12, 15, 7], [13, 5,11], [8, 6, 10],[45,54,70]]) 
print("array:\n",arr)

array:
 [[12 15  7]
 [13  5 11]
 [ 8  6 10]
 [45 54 70]]


In [64]:
arr2 = np.sort(arr) 
print("Sorted array:\n",arr2)

Sorted array:
 [[ 7 12 15]
 [ 5 11 13]
 [ 6  8 10]
 [45 54 70]]


In [65]:
arr = np.array([[12, 15, 7], [13, 5,11], [8, 6, 10],[45,54,70]]) 

# Sort multi-dimensional array along a specified axis
arr2 = np.sort(arr, axis= None) 
print(" Sorted array:\n",arr2) 

 Sorted array:
 [ 5  6  7  8 10 11 12 13 15 45 54 70]


# Concatenation

Syntax : numpy.concatenate((arr1, arr2, …), axis=0, out=None)
    
Parameters :
arr1, arr2, … : [sequence of array_like] The arrays must have the same shape, except in the dimension corresponding to axis.
    
axis : [int, optional] The axis along which the arrays will be joined. If axis is None, arrays are flattened before use. Default is 0.
out : [ndarray, optional] If provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified.

Return : [ndarray] The concatenated array.

In [71]:
arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])
  
gfg = np.concatenate((arr1, arr2), axis = 1)
  
print (gfg)

[[2 4 3 5]
 [6 8 7 9]]


In [69]:
gfg = np.concatenate((arr1, arr2), axis = None)
print(gfg)

[2 4 6 8 3 5 7 9]


# np.ma.concatenate()


We have created an array 'x' using np.ma.arrange() function.

Then, we have created another array 'y' using the same np.ma.arrange() function.

We have declared the variable 'z1' and assigned the returned value of np.concatenate() function.

We have declared variable 'z2' and assigned the returned value of np.ma.concatenate() function.

Lastly, we tried to print the value of 'z1' and 'z2'.

In [73]:
x=np.ma.arange(3)  
y=np.arange(3,6)  
x[1]=np.ma.masked  
x  
y  
 

array([3, 4, 5])

In [74]:
z1=np.concatenate([x,y])  
z2=np.ma.concatenate([x,y])  
z1  
z2 

masked_array(data=[0, --, 2, 3, 4, 5],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)

In [75]:
 L = [np.ones((3,2)), np.zeros((2,2)), np.ones((4,2))]

np.concatenate(L)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# Use NumPy.hstack() Function

Similarly, you can also concatenate arrays horizontally in Python NumPy using hstack() function. The hstack() is used to stack the array horizontally.

In [76]:
arr = np.array([4, 7, 12])
arr1 = np.array([5, 9, 15])
# Use NumPy.hstack() Functions
con = np.hstack((arr, arr1))
print(con)

[ 4  7 12  5  9 15]


# Use numpy.dstack() Function to Concatenate Arrays

Use numpy.dstack() to stack along with the height, which is the same as depth.

In [77]:
arr = np.array([4, 7, 12])
arr1 = np.array([5, 9, 15])

# Use NumPy.dstack() function to Stacking Along Height (depth)
con = np.dstack((arr, arr1))
print(con)

[[[ 4  5]
  [ 7  9]
  [12 15]]]


# Use NumPy.vstack() Function

You can use numpy.vstack() to stack arrays in sequence vertically.

In [78]:
con = np.vstack((arr, arr1))
print(con)

[[ 4  7 12]
 [ 5  9 15]]


# Use numpy.stack() Function to Join Array

Also, use numpy.stack() function to join a sequence of arrays along a new axis. You pass a sequence of arrays that you want to join to the numpy.stack() function along with the axis. If the axis is not explicitly passed it is taken as zero

In [79]:
con = np.stack((arr, arr1), axis=1)
print(con)

[[ 4  5]
 [ 7  9]
 [12 15]]
