# 1. How to create an empty and a full NumPy array?

# 2.Combining a one and a two-dimensional NumPy


 
Input: num_1d = np.arange(5)
    
        num_2d = np.arange(10).reshape(2,5)
    
output:
    One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0

1:1

2:2

3:3

4:4

0:5

1:6

2:7

3:8

4:9

# 3.How to flatten a Matrix using NumPy in Python. By using ndarray.flatten() function we can flatten a matrix to one dimension in python.

Given :
    
gfg = np.array([[2, 3], [4, 5]])

# 4. Using numpy.size() function count the number of elements along a given axis.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# 5. With the help of Numpy matrix.max() method, we can get the maximum value from given matrix.

y = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]')

# 6. With the help of matrix.sum() method, we are able to find the sum of values in a matrix 

summation = np.matrix('[5, 9, 1; 12, 23, 1; 04, 15, 6]')

# 7.  How to inverse a matrix

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# 8. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.

Input:
             
data_type = [('name', 'S15'), ('class', int), ('height', float)]
             
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]

Expected Output:
    
Original array:
    
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 ) (b'Pit', 5, 40.11)]

Sort by age, then height if class are equal:
    
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 ) (b'Nail', 6, 52.5 )]

# 9. Write a NumPy program to get the indices of the sorted elements of a given arra

Input : student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

Output:
Original array:

[1023 5202 6230 1671 1682 5241 4532]

Indices of the sorted elements of a given array:

[0 3 4 6 1 5 2]


# 10. Write a NumPy program to generate six random integers between 10 and         30.

Expected Output:
    
[-0.43262625 -1.10836787 1.80791413 0.69287463 -0.53742101]

# 11. Write a NumPy program to check two random arrays are equal or not.

Sample Output:
    
First array:
    
[1 0 1 0 1 1]

Second array:
    
[0 0 1 1 1 0]

Test above two arrays are equal or not!

False


# 12. Write a NumPy program to reverse an array (first element becomes last). 

output:

Original array:
    
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
    
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

# 13.Write a NumPy program to convert an array to a float type.

Input:
    
arr = np.array([32,45,23,65,11])

# 13. Write a NumPy program to append values to the end of an array. 

Expected Output:

Original array:

[10, 20, 30]

After append values to the end of the array:

[10 20 30 40 50 60 70 80 90]

# 14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees and vice versa. Values are stored into a NumPy array. 

Input : Array [0, 12, 45.21, 34, 99.91]
[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

Expected Output:

Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]

Values in Centigrade degrees:  [-17.78 -11.11 7.34 1.11 37.73 0. ]

Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

Values in Fahrenheit degrees:   [-0. 12. 45.21 34. 99.91 32.

# 15. Write a NumPy program to find common values between two arrays. 

Expected Output:
    
Array1: [ 0 10 20 40 60]
    
Array2: [10, 30, 40]
    
Common values between two arrays:
[10 40]

# 16.Write a NumPy program to get the unique elements of an array. 

Expected Output:
    
Original array: [10 10 20 20 30 30]
    
Unique elements of the above array:
[10 20 30]

Original array:
[[1 1]
[2 3]]

Unique elements of the above array:
[1 2 3]

# 17. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

 arr = np.array([1.0, 4.0])

# 18. Write a NumPy program to get the element-wise remainder of an array of division.