In [11]:
import numpy as np

# Numpy size()

To find python NumPy array size use size() function. The NumPy size() function has two arguments. First is an array, required an argument need to give array or array name. Second is an axis, default an argument. The axis contains none value, according to the requirement you can change it.

The np.size() function count items from a given array and give output in the form of a number as size. 

Syntax: np.size(array, axis=None)

In [12]:
arr_2D = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]]) # create NumPy 2D array
print("2D array : \n", arr_2D) # print array
 
array_size = np.size(arr_2D) # find the size of arr-2D
 
print('Size of arr_2D = ', array_size) # print size of array

2D array : 
 [[0 1 1]
 [1 0 1]
 [1 1 0]]
Size of arr_2D =  9


If you want to count how many items in a row or a column of NumPy array. Then give the axis argument as 0 or 1.

In [13]:
items_in_col = np.size(arr_2D, axis = 0) # give columns 
print("No. of items in a column = ", items_in_col )

No. of items in a column =  3


In [14]:
items_in_row = np.size(arr_2D, axis = 0)
print("No. of items in a row = ", items_in_row )

No. of items in a row =  3


You can find the size of the NumPy array using size attribute.

Syntax: array.size

In [15]:

print("Size of arr_2D = ", arr_2D.size)

Size of arr_2D =  9


In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
 
# count the number of elements along the axis.
# Here rows and columns are being treated
# as elements
 
#gives no. of rows along x-axis
print(np.size(arr, 0))
 
#gives no. of columns along y-axis
print(np.size(arr, 1))

2
4


# Python NumPy Shape 

The NumPy shape function helps to find the number of rows and columns of python NumPy array. The numpy.shape() function gives output in form of tuple (rows_no, columns_no). 

Syntax: np.shape(array)

In [17]:

arr_1D = np.array([1, 2, 3]) # create 1D array
print("One dimentional NumPy array : \n", arr_1D) # print arr_1D


One dimentional NumPy array : 
 [1 2 3]


In [18]:
shape_of_arr_1D = np.shape(arr_1D) # find shape of NumPy Array arr_1D
print("Shape of arr_1D = ", shape_of_arr_1D) # print shape_of_arr_1D

Shape of arr_1D =  (3,)


When you will find the shape of NumPy one dimensional array then np.shape() give a tuple which contains a single number. That number shows the column number respected to the array.

In [19]:
arr_2D = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]]) # create 2D array
print("Two array : \n", arr_2D) # print arr_2D
 
shape_of_arr_2D = np.shape(arr_2D) # find shape of NumPy array arr_2D
print("Shape of arr_2D = ", shape_of_arr_2D) # print shape_of_arr_2D

Two array : 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Shape of arr_2D =  (3, 3)


The np.shape() gives a return of two-dimensional array in a  pair of rows and columns tuple (rows, columns).

In [20]:
arr_3D = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]]) # create 3D array
print("Three dimensional NumPy Array : \n", arr_3D)
 
shape_of_arr_3D = np.shape(arr_3D) # find shape of NumPy array arr_3D
print("Shape of arr_3D = ", shape_of_arr_3D) # print shape_of_arr_3D

Three dimensional NumPy Array : 
 [[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
Shape of arr_3D =  (3, 3, 3)


The np.shape() gives a return of three-dimensional array in a  tuple (no. of 2D arrays, rows, columns).

# Question: Find the shape of below array and print it.

student_info = np.array([['id', 'name', 'percentage', 'pass or fail'],

                     [101, 'Ajay', 80, 'pass'], 
                     
                     [102, 'John', 75, 'pass'],
                     
                     [103, 'Abraham',33, 'fail'],
                     
                     [104, 'Oprah',52, 'pass']])
                     

# Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

Reshape From 1-D to 2-D

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



Reshape From 1-D to 3-D

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

Example:
    
Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):



In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

Check if the returned array is a copy or a view:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

The example above returns the original array, so it is a view.



# Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

Example

Convert 1D array with 8 elements to 3D array with 2x2 elements:

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

Example

Convert the array into a 1D array:

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# NumPy np.newaxis()

The newaxis() object in NumPy allows us to increase the dimensions of an array by adding new axes. This function is an alias for setting the None parameter during array declaration. However, let us explore various examples and use cases using the newaxis method.

The example shown below converts a 1-dimensional array into a 2D array as shown below:

In [34]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
new_arr = arr[np.newaxis]
print(new_arr)

[1 2 3 4 5]
[[1 2 3 4 5]]


As mentioned, the newaxis method is very similar to using the None parameter as shown below:

In [35]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
new_arr = arr[None]
print(new_arr)

[1 2 3 4 5]
[[1 2 3 4 5]]


What happens when you apply the newaxis on a 2D array. Take a look at the example below:

In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
new_arr = arr[np.newaxis]
print(new_arr)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]


You can use multiple np.newaxis at once. Multiple dimensions are added.
You can insert more than one axis as shown:

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
new_arr = arr[np.newaxis, np.newaxis]
print(new_arr)

[[1 2 3]
 [4 5 6]]
[[[[1 2 3]
   [4 5 6]]]]


In [48]:
a = np.arange(6).reshape(2, 3)
print(a)

[[0 1 2]
 [3 4 5]]


In [49]:
print(a.shape)

(2, 3)


In [50]:
print(a[:, :, np.newaxis])
print(a.shape)

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
(2, 3)


In [51]:
print(a[:, :, np.newaxis].shape)

(2, 3, 1)


In [52]:
print(a[:, np.newaxis, :])
print(a[:, np.newaxis, :].shape)

[[[0 1 2]]

 [[3 4 5]]]
(2, 1, 3)


In [53]:
print(a[np.newaxis, :, :])
print(a[np.newaxis, :, :].shape)

[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)


# Numpy array indexing

Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [55]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [56]:
# Get third and fourth elements from the following array and add them.
print(arr[2] + arr[3])

7


In [58]:
print(arr[2] * arr[3]) #multiplication

12


#Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [62]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [63]:
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.



In [64]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


# Negative Indexing

Use negative indexing to access an array from the end.

In [65]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# Numpy array indexing

Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [66]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [67]:

print(arr[4:])

[5 6 7]


In [69]:
# Slice elements from the beginning to index 4 (not included):

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# Negative slicing

In [70]:
print(arr[:-4])

[1 2 3]


In [71]:
print(arr[-3:-1])

[5 6]


In [72]:
print(arr[1:5:2])

[2 4]


In [73]:
print(arr[::2])

[1 3 5 7]


# Slicing 2-D Arrays

In [75]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [77]:
# From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [78]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# Slicing of 3-D Arrays

we can select those as before with x[1:].

All the elements are in first and second rows of both the two-dimensional array.  Row index should be represented as 0:2. 

Column index is 1:4 as the elements are in first, second and third column.  Combining all together:

In [80]:
x = np.arange(45).reshape(3,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [81]:
x[1:, 0:2, 1:4]

array([[[16, 17, 18],
        [21, 22, 23]],

       [[31, 32, 33],
        [36, 37, 38]]])

# Copy()

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

Make a copy, change the original array, and display both arrays:

In [83]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


Note : The copy SHOULD NOT be affected by the changes made to the original array.

In [86]:
x = np.array([[1,2,3],[4,5,6]])
y = x.copy()
y

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
# Creating a 3-D numpy array using np.array()
array = np.array([[12,18,44], [66,37,89],[31,47,88]])
print("Original array: ")
print(array)
 
# using numpy.copy() function
copy_array = np.copy(array)
print("\nCopied array: ")
print(copy_array)

Original array: 
[[12 18 44]
 [66 37 89]
 [31 47 88]]

Copied array: 
[[12 18 44]
 [66 37 89]
 [31 47 88]]
